import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { getStorageItem, setStorageItem } from '../utils/storage';

export type AppLanguage = 'fr' | 'en' | 'de' | 'es' | 'it' | 'pt';

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traductions
const translations: Record<AppLanguage, Record<string, string>> = {
  fr: {
    // Onboarding
    'onboarding.spanish_level': 'Quel est ton niveau en espagnol ?',
    'onboarding.spanish_level.beginner': 'Débutant',
    'onboarding.spanish_level.elementary': 'Élémentaire',
    'onboarding.spanish_level.intermediate': 'Intermédiaire',
    'onboarding.spanish_level.advanced': 'Avancé',
    'onboarding.spanish_level.native': 'Natif',
    'onboarding.native_language': 'Quelle est ta langue maternelle ?',
    'onboarding.name': 'Comment tu t\'appelles ?',
    'onboarding.gender': 'Quel est ton genre ?',
    'onboarding.age': 'Quel âge as-tu?',
    'onboarding.next': 'SUIVANT',
    'onboarding.close': 'Fermer',
    // Home
    'home.greeting': 'Salut',
    'home.take_first_lesson': 'Prends ta première leçon',
    'home.unlock_key': 'pour débloquer une clé',
    'home.call': 'APPEL',
    'home.level': 'NIVEAU',
    'home.quests': 'QUÊTES',
    'lesson.say_in_spanish': 'DIS EN ESPAGNOL',
    'lesson.learn': 'APPRENDRE',
    'lesson.feedback.correct': 'Excellent ! Tu as dit "{answer}". Très bien fait.',
    'lesson.feedback.incorrect': 'Ce n\'est pas correct. Tu as dit "{answer}". Essaie encore.',
    'quests.title': 'Quêtes',
    'quests.quest1.title': 'Termine ta première leçon',
    'quests.quest1.description': 'Termine ta première leçon pour débloquer une clé',
    'quests.quest2.title': 'Pratique 5 jours d\'affilée',
    'quests.quest2.description': 'Maintiens ta série pendant 5 jours',
    'quests.quest3.title': 'Maîtrise 10 mots',
    'quests.quest3.description': 'Apprends et maîtrise 10 nouveaux mots',
    'quests.completed': '✓ Terminé',
    // Paywall
    'paywall.access_sofia': 'accède à Sofia',
    'paywall.trial_text': '7 jours gratuits, puis 99,99 $ (8,33 $/mois)',
    'paywall.annual': 'Annuel',
    'paywall.monthly': 'Mensuel',
    'paywall.today': 'Aujourd\'hui',
    'paywall.in_5_days': 'Dans 5 jours',
    'paywall.in_7_days': 'Dans 7 jours',
    'paywall.unlock_practice': 'Débloquez une pratique illimitée avec Sofia, toutes les leçons, et plus encore.',
    'paywall.reminder_trial': 'Nous vous enverrons un rappel que votre essai se termine bientôt.',
    'paywall.charged_cancel': 'Vous serez facturé, annulez à tout moment avant.',
    'paywall.no_payment_due': 'AUCUN PAIEMENT REQUIS MAINTENANT',
    'paywall.start_free_trial': 'COMMENCER MON ESSAI GRATUIT',
    'paywall.testimonial1': '« Sofia m\'a aidé à parler espagnol en 2 semaines ! » - Marie',
    'paywall.testimonial2': '« La meilleure app pour apprendre l\'espagnol. » - Thomas',
    'paywall.testimonial3': '« Je progresse chaque jour grâce à Sofia. » - Sophie',
    // Chat
    'chat.placeholder': 'Tapez un message...',
    'chat.listening': 'Écoute...',
    // Call End
    'call.end.title': 'Appel terminé',
    'call.end.subtitle': 'Il faut te remettre sur la bonne voie !',
    'call.end.xp': 'XP',
    'call.end.gems': 'GEMMES',
    'call.end.next': 'SUIVANT',
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    // Onboarding - Questions et options
    'onboarding.placeholder.name': 'Entrez votre nom',
    'onboarding.gender.male': 'Homme',
    'onboarding.gender.female': 'Femme',
    'onboarding.gender.prefer_not': 'Préfère ne pas dire',
    'onboarding.age.under_18': 'Moins de 18 ans',
    'onboarding.age.18_24': '18 - 24',
    'onboarding.age.25_34': '25 - 34',
    'onboarding.age.35_54': '35 - 54',
    'onboarding.age.55_over': '55 ans et plus',
    'onboarding.age.prefer_not': 'Préfère ne pas dire',
    'onboarding.current_learning.question': 'Comment améliores-tu actuellement ton espagnol ?',
    'onboarding.current_learning.courses': 'Cours ou formation',
    'onboarding.current_learning.apps': 'Applications de langue',
    'onboarding.current_learning.videos': 'Vidéos ou films',
    'onboarding.current_learning.podcasts': 'Podcasts ou livres audio',
    'onboarding.current_learning.speaking': 'En parlant avec d\'autres personnes',
    'onboarding.current_learning.not_learning': 'Je n\'apprends pas actuellement',
    'onboarding.main_goal.question': 'Quel est ton objectif principal pour améliorer ton espagnol ?',
    'onboarding.main_goal.work': 'Travail',
    'onboarding.main_goal.living_abroad': 'Vivre à l\'étranger',
    'onboarding.main_goal.traveling': 'Voyager',
    'onboarding.main_goal.skills': 'Développer mes compétences',
    'onboarding.main_goal.friends': 'Parler avec des amis',
    'onboarding.main_goal.studying': 'Étudier',
    'onboarding.speaking_frequency.question': 'À quelle fréquence parles-tu espagnol dans ta vie quotidienne ?',
    'onboarding.speaking_frequency.everyday': 'Tous les jours',
    'onboarding.speaking_frequency.few_week': 'Quelques jours par semaine',
    'onboarding.speaking_frequency.few_month': 'Quelques jours par mois',
    'onboarding.speaking_frequency.never': 'Jamais',
    'onboarding.fear.question': 'As-tu peur d\'avoir l\'air ridicule quand tu parles espagnol ?',
    'onboarding.fear.no': 'Non',
    'onboarding.fear.maybe': 'Peut-être',
    'onboarding.fear.yes': 'Oui',
    'onboarding.improvement.question': 'Où veux-tu t\'améliorer ?',
    'onboarding.improvement.speaking': 'Parler avec confiance',
    'onboarding.improvement.pronunciation': 'Améliorer la prononciation',
    'onboarding.improvement.vocabulary': 'Enrichir le vocabulaire',
    'onboarding.improvement.grammar': 'Être bon en grammaire',
    'onboarding.improvement.understanding': 'Comprendre les locuteurs natifs',
    'onboarding.improvement.writing': 'Écrire plus couramment',
    'onboarding.improvement.else': 'Autre chose',
    'onboarding.interests.question': 'Quels sujets t\'intéressent ?',
    'onboarding.interests.subtitle': 'Nous rendrons votre pratique de l\'espagnol plus amusante',
    'onboarding.interests.memes': 'Mèmes',
    'onboarding.interests.humor': 'Humour',
    'onboarding.interests.tech': 'Technologie',
    'onboarding.interests.business': 'Business',
    'onboarding.interests.games': 'Jeux vidéo',
    'onboarding.interests.music': 'Musique',
    'onboarding.interests.movies': 'Films',
    'onboarding.interests.news': 'Actualités',
    'onboarding.interests.books': 'Livres',
    'onboarding.interests.podcasts': 'Podcasts',
    'onboarding.interests.fitness': 'Fitness',
    'onboarding.interests.food': 'Nourriture',
    'onboarding.interests.crafts': 'Artisanat',
    'onboarding.interests.travel': 'Voyage',
    'onboarding.interests.science': 'Science',
    'onboarding.commitment.question': 'Quel est ton engagement pour progresser ?',
    'onboarding.commitment.7_days': 'Série de 7 jours',
    'onboarding.commitment.14_days': 'Série de 14 jours',
    'onboarding.commitment.30_days': 'Série de 30 jours',
    'onboarding.commitment.50_days': 'Série de 50 jours',
    'onboarding.commitment.promising': 'Prometteur',
    'onboarding.commitment.determined': 'Déterminé',
    'onboarding.commitment.impressive': 'Impressionnant',
    'onboarding.commitment.unstoppable': 'Imparable',
    'onboarding.motivation.title': 'Engagement de motivation',
    'onboarding.motivation.message': 'Pour atteindre ce que je veux, je dois progresser.\n\nJe m\'engage donc à atteindre mes objectifs et à m\'améliorer.\n\nEt je fais confiance à Sofia pour me guider et m\'aider à parler espagnol couramment.',
    'onboarding.motivation.press_hold': 'Appuie et maintiens',
    'onboarding.future.title': 'C\'est moi',
    'onboarding.future.sender': 'Vous du futur',
    'onboarding.future.date': '15 novembre 2025',
    'onboarding.future.message': 'Oui, c\'est vous du futur. Je vous écris depuis 2025 car aujourd\'hui est un jour important pour vous. Pour nous !\n\nLe 15 novembre 2025 est le jour où nous avons changé nos vies.\n\nAujourd\'hui je me sens bien et je parle espagnol couramment. Grâce à la décision de développement personnel que vous êtes sur le point de prendre.\n\nÀ bientôt,\nVous du futur',
    'onboarding.plan.title': 'Je crée votre plan d\'étude personnalisé',
    'onboarding.plan.subtitle': 'Adapté à votre niveau et à vos besoins',
    'onboarding.plan.message': 'Utiliser des matériaux liés à vos intérêts améliore l\'apprentissage du vocabulaire de 30%.',
    'onboarding.plan.sofia': 'Chaque leçon est construite à partir de ce dont vous discutez avec moi.',
    'onboarding.comparison.title': 'Ils vous font cliquer, Sofia vous fait parler',
    'onboarding.notifications.question': 'Avec moi, tu n\'oublieras pas de t\'entraîner',
    'onboarding.first_session': 'Incroyable—votre entraînement commence officiellement 🎉 Je vais maintenant vous poser de vraies questions, et vous répondrez en espagnol. Prêt pour votre première mini-conversation ?',
  },
  en: {
    // Onboarding
    'onboarding.spanish_level': 'What is your level in Spanish?',
    'onboarding.spanish_level.beginner': 'Beginner',
    'onboarding.spanish_level.elementary': 'Elementary',
    'onboarding.spanish_level.intermediate': 'Intermediate',
    'onboarding.spanish_level.advanced': 'Advanced',
    'onboarding.spanish_level.native': 'Native',
    'onboarding.native_language': 'What is your native language?',
    'onboarding.name': 'What is your name?',
    'onboarding.gender': 'What is your gender?',
    'onboarding.age': 'How old are you?',
    'onboarding.next': 'NEXT',
    'onboarding.close': 'Close',
    // Onboarding - Options
    'onboarding.placeholder.name': 'Enter your name',
    'onboarding.gender.male': 'Male',
    'onboarding.gender.female': 'Female',
    'onboarding.gender.prefer_not': 'Prefer not to say',
    'onboarding.age.under_18': 'Under 18',
    'onboarding.age.18_24': '18 - 24',
    'onboarding.age.25_34': '25 - 34',
    'onboarding.age.35_54': '35 - 54',
    'onboarding.age.55_over': '55 and over',
    'onboarding.age.prefer_not': 'Prefer not to say',
    'onboarding.current_learning.question': 'How are you currently improving your Spanish?',
    'onboarding.current_learning.courses': 'Courses or training',
    'onboarding.current_learning.apps': 'Language apps',
    'onboarding.current_learning.videos': 'Videos or movies',
    'onboarding.current_learning.podcasts': 'Podcasts or audiobooks',
    'onboarding.current_learning.speaking': 'By speaking with other people',
    'onboarding.current_learning.not_learning': 'I\'m not currently learning',
    'onboarding.main_goal.question': 'What is your main goal for improving your Spanish?',
    'onboarding.main_goal.work': 'Work',
    'onboarding.main_goal.living_abroad': 'Living abroad',
    'onboarding.main_goal.traveling': 'Traveling',
    'onboarding.main_goal.skills': 'Developing my skills',
    'onboarding.main_goal.friends': 'Speaking with friends',
    'onboarding.main_goal.studying': 'Studying',
    'onboarding.speaking_frequency.question': 'How often do you speak Spanish in your daily life?',
    'onboarding.speaking_frequency.everyday': 'Every day',
    'onboarding.speaking_frequency.few_week': 'A few days a week',
    'onboarding.speaking_frequency.few_month': 'A few days a month',
    'onboarding.speaking_frequency.never': 'Never',
    'onboarding.fear.question': 'Are you afraid of sounding silly when you speak Spanish?',
    'onboarding.fear.no': 'No',
    'onboarding.fear.maybe': 'Maybe',
    'onboarding.fear.yes': 'Yes',
    'onboarding.improvement.question': 'Where do you want to improve?',
    'onboarding.improvement.speaking': 'Speaking with confidence',
    'onboarding.improvement.pronunciation': 'Improving pronunciation',
    'onboarding.improvement.vocabulary': 'Enriching vocabulary',
    'onboarding.improvement.grammar': 'Being good at grammar',
    'onboarding.improvement.understanding': 'Understanding native speakers',
    'onboarding.improvement.writing': 'Writing more fluently',
    'onboarding.improvement.else': 'Something else',
    'onboarding.interests.question': 'What topics interest you?',
    'onboarding.interests.subtitle': 'We\'ll make your Spanish practice more fun',
    'onboarding.interests.memes': 'Memes',
    'onboarding.interests.humor': 'Humor',
    'onboarding.interests.tech': 'Tech',
    'onboarding.interests.business': 'Business',
    'onboarding.interests.games': 'Video games',
    'onboarding.interests.music': 'Music',
    'onboarding.interests.movies': 'Movies',
    'onboarding.interests.news': 'News',
    'onboarding.interests.books': 'Books',
    'onboarding.interests.podcasts': 'Podcasts',
    'onboarding.interests.fitness': 'Fitness',
    'onboarding.interests.food': 'Food',
    'onboarding.interests.crafts': 'Crafts',
    'onboarding.interests.travel': 'Travel',
    'onboarding.interests.science': 'Science',
    'onboarding.commitment.question': 'What is your commitment to progress?',
    'onboarding.commitment.7_days': '7-day streak',
    'onboarding.commitment.14_days': '14-day streak',
    'onboarding.commitment.30_days': '30-day streak',
    'onboarding.commitment.50_days': '50-day streak',
    'onboarding.commitment.promising': 'Promising',
    'onboarding.commitment.determined': 'Determined',
    'onboarding.commitment.impressive': 'Impressive',
    'onboarding.commitment.unstoppable': 'Unstoppable',
    'onboarding.motivation.title': 'Motivation commitment',
    'onboarding.motivation.message': 'To achieve what I want, I must progress.\n\nI therefore commit to reaching my goals and improving myself.\n\nAnd I trust Sofia to guide me along the way and help me speak Spanish fluently.',
    'onboarding.motivation.press_hold': 'Press and hold',
    'onboarding.future.title': 'It\'s me',
    'onboarding.future.sender': 'Future you',
    'onboarding.future.date': 'November 15, 2025',
    'onboarding.future.message': 'Yes, it\'s you from the future. I\'m writing to you from 2025 because today is an important day for you. For us!\n\nNovember 15, 2025 is the day we changed our lives.\n\nToday I feel great and I speak Spanish fluently. Thanks to the personal development decision you are about to make.\n\nSee you soon,\nFuture you',
    'onboarding.plan.title': 'I\'m creating your personalized study plan',
    'onboarding.plan.subtitle': 'Adapted to your level and needs',
    'onboarding.plan.message': 'Using materials related to your interests improves vocabulary learning by 30%.',
    'onboarding.plan.sofia': 'Each lesson is built from what you discuss with me.',
    'onboarding.comparison.title': 'They make you click, Sofia makes you speak',
    'onboarding.notifications.question': 'With me, you won\'t forget to practice',
    'onboarding.first_session': 'Amazing—your training officially begins 🎉 I\'ll now ask you real questions, and you\'ll answer in Spanish. Ready for your first mini-conversation?',
    // Home
    'home.greeting': 'Hello',
    'home.take_first_lesson': 'Take your first lesson',
    'home.unlock_key': 'to unlock a key',
    'home.call': 'CALL',
    'home.level': 'LEVEL',
    'home.quests': 'QUESTS',
    'lesson.say_in_spanish': 'SAY IN SPANISH',
    'lesson.learn': 'LEARN',
    'lesson.feedback.correct': 'Excellent! You said "{answer}". Well done.',
    'lesson.feedback.incorrect': 'Not correct. You said "{answer}". Try again.',
    'quests.title': 'Quests',
    'quests.quest1.title': 'Complete your first lesson',
    'quests.quest1.description': 'Finish your first lesson to unlock a key',
    'quests.quest2.title': 'Practice 5 days in a row',
    'quests.quest2.description': 'Maintain your streak for 5 days',
    'quests.quest3.title': 'Master 10 words',
    'quests.quest3.description': 'Learn and master 10 new words',
    'quests.completed': '✓ Completed',
    // Paywall
    'paywall.access_sofia': 'access Sofia',
    'paywall.trial_text': '7 days free, then $99.99 ($8.33/month)',
    'paywall.annual': 'Annual',
    'paywall.monthly': 'Monthly',
    'paywall.today': 'Today',
    'paywall.in_5_days': 'In 5 days',
    'paywall.in_7_days': 'In 7 days',
    'paywall.unlock_practice': 'Unlock unlimited practice with Sofia, all lessons, and more.',
    'paywall.reminder_trial': 'We\'ll send you a reminder that your trial is ending soon.',
    'paywall.charged_cancel': 'You\'ll be charged, cancel anytime before.',
    'paywall.no_payment_due': 'NO PAYMENT REQUIRED NOW',
    'paywall.start_free_trial': 'START MY FREE TRIAL',
    'paywall.testimonial1': '"Sofia helped me speak Spanish in 2 weeks!" - Marie',
    'paywall.testimonial2': '"The best app to learn Spanish." - Thomas',
    'paywall.testimonial3': '"I progress every day thanks to Sofia." - Sophie',
    // Chat
    'chat.placeholder': 'Type a message...',
    'chat.listening': 'Listening...',
    // Call End
    'call.end.title': 'Call ended',
    'call.end.subtitle': 'You need to get back on track!',
    'call.end.xp': 'XP',
    'call.end.gems': 'GEMS',
    'call.end.next': 'NEXT',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
  },
  de: {
    // Onboarding
    'onboarding.spanish_level': 'Wie ist dein Spanischniveau?',
    'onboarding.spanish_level.beginner': 'Anfänger',
    'onboarding.spanish_level.elementary': 'Grundstufe',
    'onboarding.spanish_level.intermediate': 'Mittelstufe',
    'onboarding.spanish_level.advanced': 'Fortgeschritten',
    'onboarding.spanish_level.native': 'Muttersprachler',
    'onboarding.native_language': 'Was ist deine Muttersprache?',
    'onboarding.name': 'Wie heißt du?',
    'onboarding.gender': 'Was ist dein Geschlecht?',
    'onboarding.age': 'Wie alt bist du?',
    'onboarding.next': 'WEITER',
    'onboarding.close': 'Schließen',
    // Home
    'home.greeting': 'Hallo',
    'home.take_first_lesson': 'Nimm deine erste Lektion',
    'home.unlock_key': 'um einen Schlüssel freizuschalten',
    'home.call': 'ANRUF',
    'home.level': 'STUFE',
    'home.quests': 'QUESTS',
    'lesson.say_in_spanish': 'SAG AUF SPANISCH',
    'lesson.learn': 'LERNEN',
    'lesson.feedback.correct': 'Ausgezeichnet! Du hast "{answer}" gesagt. Sehr gut gemacht.',
    'lesson.feedback.incorrect': 'Das ist nicht richtig. Du hast "{answer}" gesagt. Versuche es erneut.',
    'quests.title': 'Quests',
    'quests.quest1.title': 'Vervollständige deine erste Lektion',
    'quests.quest1.description': 'Beende deine erste Lektion, um einen Schlüssel freizuschalten',
    'quests.quest2.title': '5 Tage hintereinander üben',
    'quests.quest2.description': 'Halte deine Serie 5 Tage lang aufrecht',
    'quests.quest3.title': 'Meistere 10 Wörter',
    'quests.quest3.description': 'Lerne und meistere 10 neue Wörter',
    'quests.completed': '✓ Abgeschlossen',
    // Paywall
    'paywall.access_sofia': 'Zugang zu Sofia',
    'paywall.trial_text': '7 Tage kostenlos, dann 99,99 $ (8,33 $/Monat)',
    'paywall.annual': 'Jährlich',
    'paywall.monthly': 'Monatlich',
    'paywall.today': 'Heute',
    'paywall.in_5_days': 'In 5 Tagen',
    'paywall.in_7_days': 'In 7 Tagen',
    'paywall.unlock_practice': 'Schalte unbegrenztes Üben mit Sofia, alle Lektionen und mehr frei.',
    'paywall.reminder_trial': 'Wir senden dir eine Erinnerung, dass deine Testversion bald endet.',
    'paywall.charged_cancel': 'Du wirst belastet, kündige jederzeit vorher.',
    'paywall.no_payment_due': 'KEINE ZAHLUNG JETZT ERFORDERLICH',
    'paywall.start_free_trial': 'KOSTENLOSE TESTVERSION STARTEN',
    'paywall.testimonial1': '"Sofia half mir, in 2 Wochen Spanisch zu sprechen!" - Marie',
    'paywall.testimonial2': '"Die beste App zum Spanischlernen." - Thomas',
    'paywall.testimonial3': '"Ich mache jeden Tag Fortschritte dank Sofia." - Sophie',
    // Chat
    'chat.placeholder': 'Nachricht eingeben...',
    'chat.listening': 'Höre zu...',
    // Call End
    'call.end.title': 'Anruf beendet',
    'call.end.subtitle': 'Du musst wieder auf den richtigen Weg kommen!',
    'call.end.xp': 'XP',
    'call.end.gems': 'EDELSTEINE',
    'call.end.next': 'WEITER',
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    // Onboarding - Questions et options
    'onboarding.placeholder.name': 'Geben Sie Ihren Namen ein',
    'onboarding.gender.male': 'Männlich',
    'onboarding.gender.female': 'Weiblich',
    'onboarding.gender.prefer_not': 'Möchte nicht sagen',
    'onboarding.age.under_18': 'Unter 18',
    'onboarding.age.18_24': '18 - 24',
    'onboarding.age.25_34': '25 - 34',
    'onboarding.age.35_54': '35 - 54',
    'onboarding.age.55_over': '55 und älter',
    'onboarding.age.prefer_not': 'Möchte nicht sagen',
    'onboarding.current_learning.question': 'Wie verbesserst du derzeit dein Spanisch?',
    'onboarding.current_learning.courses': 'Kurse oder Training',
    'onboarding.current_learning.apps': 'Sprach-Apps',
    'onboarding.current_learning.videos': 'Videos oder Filme',
    'onboarding.current_learning.podcasts': 'Podcasts oder Hörbücher',
    'onboarding.current_learning.speaking': 'Durch Gespräche mit anderen',
    'onboarding.current_learning.not_learning': 'Ich lerne derzeit nicht',
    'onboarding.main_goal.question': 'Was ist dein Hauptziel, um dein Spanisch zu verbessern?',
    'onboarding.main_goal.work': 'Arbeit',
    'onboarding.main_goal.living_abroad': 'Im Ausland leben',
    'onboarding.main_goal.traveling': 'Reisen',
    'onboarding.main_goal.skills': 'Meine Fähigkeiten entwickeln',
    'onboarding.main_goal.friends': 'Mit Freunden sprechen',
    'onboarding.main_goal.studying': 'Studieren',
    'onboarding.speaking_frequency.question': 'Wie oft sprichst du Spanisch in deinem täglichen Leben?',
    'onboarding.speaking_frequency.everyday': 'Jeden Tag',
    'onboarding.speaking_frequency.few_week': 'Ein paar Tage pro Woche',
    'onboarding.speaking_frequency.few_month': 'Ein paar Tage pro Monat',
    'onboarding.speaking_frequency.never': 'Nie',
    'onboarding.fear.question': 'Hast du Angst, dumm zu klingen, wenn du Spanisch sprichst?',
    'onboarding.fear.no': 'Nein',
    'onboarding.fear.maybe': 'Vielleicht',
    'onboarding.fear.yes': 'Ja',
    'onboarding.improvement.question': 'Wo möchtest du dich verbessern?',
    'onboarding.improvement.speaking': 'Mit Selbstvertrauen sprechen',
    'onboarding.improvement.pronunciation': 'Aussprache verbessern',
    'onboarding.improvement.vocabulary': 'Wortschatz erweitern',
    'onboarding.improvement.grammar': 'Gut in Grammatik sein',
    'onboarding.improvement.understanding': 'Muttersprachler verstehen',
    'onboarding.improvement.writing': 'Fließender schreiben',
    'onboarding.improvement.else': 'Etwas anderes',
    'onboarding.interests.question': 'Welche Themen interessieren dich?',
    'onboarding.interests.subtitle': 'Wir machen Ihr Spanisch-Training unterhaltsamer',
    'onboarding.interests.memes': 'Memes',
    'onboarding.interests.humor': 'Humor',
    'onboarding.interests.tech': 'Technik',
    'onboarding.interests.business': 'Business',
    'onboarding.interests.games': 'Videospiele',
    'onboarding.interests.music': 'Musik',
    'onboarding.interests.movies': 'Filme',
    'onboarding.interests.news': 'Nachrichten',
    'onboarding.interests.books': 'Bücher',
    'onboarding.interests.podcasts': 'Podcasts',
    'onboarding.interests.fitness': 'Fitness',
    'onboarding.interests.food': 'Essen',
    'onboarding.interests.crafts': 'Handwerk',
    'onboarding.interests.travel': 'Reisen',
    'onboarding.interests.science': 'Wissenschaft',
    'onboarding.commitment.question': 'Wie ist Ihr Engagement für den Fortschritt?',
    'onboarding.commitment.7_days': '7-Tage-Serie',
    'onboarding.commitment.14_days': '14-Tage-Serie',
    'onboarding.commitment.30_days': '30-Tage-Serie',
    'onboarding.commitment.50_days': '50-Tage-Serie',
    'onboarding.commitment.promising': 'Vielversprechend',
    'onboarding.commitment.determined': 'Entschlossen',
    'onboarding.commitment.impressive': 'Beeindruckend',
    'onboarding.commitment.unstoppable': 'Unaufhaltsam',
    'onboarding.motivation.title': 'Motivationsverpflichtung',
    'onboarding.motivation.message': 'Um das zu erreichen, was ich will, muss ich Fortschritte machen.\n\nDaher verpflichte ich mich, meine Ziele zu erreichen und mich zu verbessern.\n\nUnd ich vertraue Sofia, mich auf dem Weg zu führen und mir zu helfen, fließend Spanisch zu sprechen.',
    'onboarding.motivation.press_hold': 'Drücken und halten',
    'onboarding.future.title': 'Ich bin es',
    'onboarding.future.sender': 'Zukünftiges Du',
    'onboarding.future.date': '15. November 2025',
    'onboarding.future.message': 'Ja, du bist es aus der Zukunft. Ich schreibe dir aus dem Jahr 2025, weil heute ein wichtiger Tag für dich ist. Für uns!\n\nDer 15. November 2025 ist der Tag, an dem wir unser Leben verändert haben.\n\nHeute fühle ich mich großartig und spreche fließend Spanisch. Dank der Entscheidung zur persönlichen Entwicklung, die du gleich treffen wirst.\n\nBis bald,\nZukünftiges Du',
    'onboarding.plan.title': 'Ich erstelle Ihren personalisierten Lernplan',
    'onboarding.plan.subtitle': 'Angepasst an Ihr Niveau und Ihre Bedürfnisse',
    'onboarding.plan.message': 'Die Verwendung von Materialien, die mit Ihren Interessen zusammenhängen, verbessert das Vokabellernen um 30%.',
    'onboarding.plan.sofia': 'Jede Lektion wird aus dem aufgebaut, worüber Sie mit mir sprechen.',
    'onboarding.comparison.title': 'Sie lassen Sie klicken, Sofia lässt Sie sprechen',
    'onboarding.notifications.question': 'Mit mir wirst du nicht vergessen zu üben',
    'onboarding.first_session': 'Erstaunlich—Ihr Training beginnt offiziell 🎉 Ich werde Ihnen jetzt echte Fragen stellen, und Sie werden auf Spanisch antworten. Bereit für Ihre erste Mini-Unterhaltung?',
  },
  es: {
    // Onboarding
    'onboarding.spanish_level': '¿Cuál es tu nivel de español?',
    'onboarding.spanish_level.beginner': 'Principiante',
    'onboarding.spanish_level.elementary': 'Elemental',
    'onboarding.spanish_level.intermediate': 'Intermedio',
    'onboarding.spanish_level.advanced': 'Avanzado',
    'onboarding.spanish_level.native': 'Nativo',
    'onboarding.native_language': '¿Cuál es tu idioma nativo?',
    'onboarding.name': '¿Cómo te llamas?',
    'onboarding.gender': '¿Cuál es tu género?',
    'onboarding.age': '¿Cuántos años tienes?',
    'onboarding.next': 'SIGUIENTE',
    'onboarding.close': 'Cerrar',
    // Home
    'home.greeting': 'Hola',
    'home.take_first_lesson': 'Toma tu primera lección',
    'home.unlock_key': 'para desbloquear una llave',
    'home.call': 'LLAMADA',
    'home.level': 'NIVEL',
    'home.quests': 'MISIONES',
    'lesson.say_in_spanish': 'DI EN ESPAÑOL',
    'lesson.learn': 'APRENDER',
    'lesson.feedback.correct': '¡Excelente! Has dicho "{answer}". Muy bien hecho.',
    'lesson.feedback.incorrect': 'No es correcto. Has dicho "{answer}". Intenta de nuevo.',
    'quests.title': 'Misiones',
    'quests.quest1.title': 'Completa tu primera lección',
    'quests.quest1.description': 'Termina tu primera lección para desbloquear una llave',
    'quests.quest2.title': 'Practica 5 días seguidos',
    'quests.quest2.description': 'Mantén tu racha durante 5 días',
    'quests.quest3.title': 'Domina 10 palabras',
    'quests.quest3.description': 'Aprende y domina 10 palabras nuevas',
    'quests.completed': '✓ Completado',
    // Paywall
    'paywall.access_sofia': 'accede a Sofia',
    'paywall.trial_text': '7 días gratis, luego $99.99 ($8.33/mes)',
    'paywall.annual': 'Anual',
    'paywall.monthly': 'Mensual',
    'paywall.today': 'Hoy',
    'paywall.in_5_days': 'En 5 días',
    'paywall.in_7_days': 'En 7 días',
    'paywall.unlock_practice': 'Desbloquea práctica ilimitada con Sofia, todas las lecciones y más.',
    'paywall.reminder_trial': 'Te enviaremos un recordatorio de que tu prueba está por terminar.',
    'paywall.charged_cancel': 'Se te cobrará, cancela en cualquier momento antes.',
    'paywall.no_payment_due': 'NO SE REQUIERE PAGO AHORA',
    'paywall.start_free_trial': 'INICIAR MI PRUEBA GRATIS',
    'paywall.testimonial1': '"¡Sofia me ayudó a hablar español en 2 semanas!" - Marie',
    'paywall.testimonial2': '"La mejor app para aprender español." - Thomas',
    'paywall.testimonial3': '"Progreso cada día gracias a Sofia." - Sophie',
    // Chat
    'chat.placeholder': 'Escribe un mensaje...',
    'chat.listening': 'Escuchando...',
    // Call End
    'call.end.title': 'Llamada terminada',
    'call.end.subtitle': '¡Necesitas volver al buen camino!',
    'call.end.xp': 'XP',
    'call.end.gems': 'GEMAS',
    'call.end.next': 'SIGUIENTE',
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    // Onboarding - Questions et options
    'onboarding.placeholder.name': 'Ingresa tu nombre',
    'onboarding.gender.male': 'Masculino',
    'onboarding.gender.female': 'Femenino',
    'onboarding.gender.prefer_not': 'Prefiero no decir',
    'onboarding.age.under_18': 'Menos de 18',
    'onboarding.age.18_24': '18 - 24',
    'onboarding.age.25_34': '25 - 34',
    'onboarding.age.35_54': '35 - 54',
    'onboarding.age.55_over': '55 y más',
    'onboarding.age.prefer_not': 'Prefiero no decir',
    'onboarding.current_learning.question': '¿Cómo estás mejorando tu español actualmente?',
    'onboarding.current_learning.courses': 'Cursos o formación',
    'onboarding.current_learning.apps': 'Aplicaciones de idiomas',
    'onboarding.current_learning.videos': 'Videos o películas',
    'onboarding.current_learning.podcasts': 'Podcasts o audiolibros',
    'onboarding.current_learning.speaking': 'Hablando con otras personas',
    'onboarding.current_learning.not_learning': 'No estoy aprendiendo actualmente',
    'onboarding.main_goal.question': '¿Cuál es tu objetivo principal para mejorar tu español?',
    'onboarding.main_goal.work': 'Trabajo',
    'onboarding.main_goal.living_abroad': 'Vivir en el extranjero',
    'onboarding.main_goal.traveling': 'Viajar',
    'onboarding.main_goal.skills': 'Desarrollar mis habilidades',
    'onboarding.main_goal.friends': 'Hablar con amigos',
    'onboarding.main_goal.studying': 'Estudiar',
    'onboarding.speaking_frequency.question': '¿Con qué frecuencia hablas español en tu vida diaria?',
    'onboarding.speaking_frequency.everyday': 'Todos los días',
    'onboarding.speaking_frequency.few_week': 'Algunos días a la semana',
    'onboarding.speaking_frequency.few_month': 'Algunos días al mes',
    'onboarding.speaking_frequency.never': 'Nunca',
    'onboarding.fear.question': '¿Tienes miedo de sonar tonto cuando hablas español?',
    'onboarding.fear.no': 'No',
    'onboarding.fear.maybe': 'Tal vez',
    'onboarding.fear.yes': 'Sí',
    'onboarding.improvement.question': '¿Dónde quieres mejorar?',
    'onboarding.improvement.speaking': 'Hablar con confianza',
    'onboarding.improvement.pronunciation': 'Mejorar la pronunciación',
    'onboarding.improvement.vocabulary': 'Enriquecer el vocabulario',
    'onboarding.improvement.grammar': 'Ser bueno en gramática',
    'onboarding.improvement.understanding': 'Entender hablantes nativos',
    'onboarding.improvement.writing': 'Escribir con más fluidez',
    'onboarding.improvement.else': 'Algo más',
    'onboarding.interests.question': '¿Qué temas te interesan?',
    'onboarding.interests.subtitle': 'Haremos tu práctica de español más divertida',
    'onboarding.interests.memes': 'Memes',
    'onboarding.interests.humor': 'Humor',
    'onboarding.interests.tech': 'Tecnología',
    'onboarding.interests.business': 'Negocios',
    'onboarding.interests.games': 'Videojuegos',
    'onboarding.interests.music': 'Música',
    'onboarding.interests.movies': 'Películas',
    'onboarding.interests.news': 'Noticias',
    'onboarding.interests.books': 'Libros',
    'onboarding.interests.podcasts': 'Podcasts',
    'onboarding.interests.fitness': 'Fitness',
    'onboarding.interests.food': 'Comida',
    'onboarding.interests.crafts': 'Artesanía',
    'onboarding.interests.travel': 'Viajes',
    'onboarding.interests.science': 'Ciencia',
    'onboarding.commitment.question': '¿Cuál es tu compromiso para progresar?',
    'onboarding.commitment.7_days': 'Racha de 7 días',
    'onboarding.commitment.14_days': 'Racha de 14 días',
    'onboarding.commitment.30_days': 'Racha de 30 días',
    'onboarding.commitment.50_days': 'Racha de 50 días',
    'onboarding.commitment.promising': 'Prometedor',
    'onboarding.commitment.determined': 'Determinado',
    'onboarding.commitment.impressive': 'Impresionante',
    'onboarding.commitment.unstoppable': 'Imparable',
    'onboarding.motivation.title': 'Compromiso de motivación',
    'onboarding.motivation.message': 'Para lograr lo que quiero, debo progresar.\n\nPor lo tanto, me comprometo a alcanzar mis objetivos y mejorarme.\n\nY confío en Sofia para guiarme en el camino y ayudarme a hablar español con fluidez.',
    'onboarding.future.title': 'Soy yo',
    'onboarding.future.sender': 'Tú del futuro',
    'onboarding.future.date': '15 de noviembre de 2025',
    'onboarding.future.message': 'Sí, eres tú del futuro. Te escribo desde 2025 porque hoy es un día importante para ti. ¡Para nosotros!\n\nEl 15 de noviembre de 2025 es el día en que cambiamos nuestras vidas.\n\nHoy me siento genial y hablo español con fluidez. Gracias a la decisión de desarrollo personal que estás a punto de tomar.\n\nHasta pronto,\nTú del futuro',
    'onboarding.plan.title': 'Estoy creando tu plan de estudio personalizado',
    'onboarding.plan.subtitle': 'Adaptado a tu nivel y necesidades',
    'onboarding.plan.message': 'Usar materiales relacionados con tus intereses mejora el aprendizaje de vocabulario en un 30%.',
    'onboarding.plan.sofia': 'Cada lección se construye a partir de lo que discutes conmigo.',
    'onboarding.comparison.title': 'Ellos te hacen hacer clic, Sofia te hace hablar',
    'onboarding.notifications.question': 'Conmigo, no olvidarás practicar',
    'onboarding.first_session': 'Increíble—tu entrenamiento comienza oficialmente 🎉 Ahora te haré preguntas reales, y responderás en español. ¿Listo para tu primera mini-conversación?',
  },
  it: {
    // Onboarding
    'onboarding.spanish_level': 'Qual è il tuo livello di spagnolo?',
    'onboarding.spanish_level.beginner': 'Principiante',
    'onboarding.spanish_level.elementary': 'Elementare',
    'onboarding.spanish_level.intermediate': 'Intermedio',
    'onboarding.spanish_level.advanced': 'Avanzato',
    'onboarding.spanish_level.native': 'Madrelingua',
    'onboarding.native_language': 'Qual è la tua lingua madre?',
    'onboarding.name': 'Come ti chiami?',
    'onboarding.gender': 'Qual è il tuo genere?',
    'onboarding.age': 'Quanti anni hai?',
    'onboarding.next': 'AVANTI',
    'onboarding.close': 'Chiudi',
    // Home
    'home.greeting': 'Ciao',
    'home.take_first_lesson': 'Prendi la tua prima lezione',
    'home.unlock_key': 'per sbloccare una chiave',
    'home.call': 'CHIAMATA',
    'home.level': 'LIVELLO',
    'home.quests': 'MISSIONI',
    'lesson.say_in_spanish': 'DI IN SPAGNOLO',
    'lesson.learn': 'IMPARA',
    'lesson.feedback.correct': 'Eccellente! Hai detto "{answer}". Molto bene fatto.',
    'lesson.feedback.incorrect': 'Non è corretto. Hai detto "{answer}". Riprova.',
    'quests.title': 'Missioni',
    'quests.quest1.title': 'Completa la tua prima lezione',
    'quests.quest1.description': 'Termina la tua prima lezione per sbloccare una chiave',
    'quests.quest2.title': 'Pratica 5 giorni di fila',
    'quests.quest2.description': 'Mantieni la tua serie per 5 giorni',
    'quests.quest3.title': 'Padroneggia 10 parole',
    'quests.quest3.description': 'Impara e padroneggia 10 nuove parole',
    'quests.completed': '✓ Completato',
    // Paywall
    'paywall.access_sofia': 'accedi a Sofia',
    'paywall.trial_text': '7 giorni gratuiti, poi $99.99 ($8.33/mese)',
    'paywall.annual': 'Annuale',
    'paywall.monthly': 'Mensile',
    'paywall.today': 'Oggi',
    'paywall.in_5_days': 'Tra 5 giorni',
    'paywall.in_7_days': 'Tra 7 giorni',
    'paywall.unlock_practice': 'Sblocca pratica illimitata con Sofia, tutte le lezioni e altro ancora.',
    'paywall.reminder_trial': 'Ti invieremo un promemoria che la tua prova sta per finire.',
    'paywall.charged_cancel': 'Sarai addebitato, cancella in qualsiasi momento prima.',
    'paywall.no_payment_due': 'NESSUN PAGAMENTO RICHIESTO ORA',
    'paywall.start_free_trial': 'INIZIA LA MIA PROVA GRATUITA',
    'paywall.testimonial1': '"Sofia mi ha aiutato a parlare spagnolo in 2 settimane!" - Marie',
    'paywall.testimonial2': '"La migliore app per imparare lo spagnolo." - Thomas',
    'paywall.testimonial3': '"Progredisco ogni giorno grazie a Sofia." - Sophie',
    // Chat
    'chat.placeholder': 'Scrivi un messaggio...',
    'chat.listening': 'In ascolto...',
    // Call End
    'call.end.title': 'Chiamata terminata',
    'call.end.subtitle': 'Devi tornare sulla buona strada!',
    'call.end.xp': 'XP',
    'call.end.gems': 'GEMME',
    'call.end.next': 'AVANTI',
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    // Onboarding - Questions et options
    'onboarding.placeholder.name': 'Inserisci il tuo nome',
    'onboarding.gender.male': 'Maschio',
    'onboarding.gender.female': 'Femmina',
    'onboarding.gender.prefer_not': 'Preferisco non dirlo',
    'onboarding.age.under_18': 'Sotto i 18',
    'onboarding.age.18_24': '18 - 24',
    'onboarding.age.25_34': '25 - 34',
    'onboarding.age.35_54': '35 - 54',
    'onboarding.age.55_over': '55 e oltre',
    'onboarding.age.prefer_not': 'Preferisco non dirlo',
    'onboarding.current_learning.question': 'Come stai migliorando il tuo spagnolo attualmente?',
    'onboarding.current_learning.courses': 'Corsi o formazione',
    'onboarding.current_learning.apps': 'App linguistiche',
    'onboarding.current_learning.videos': 'Video o film',
    'onboarding.current_learning.podcasts': 'Podcast o audiolibri',
    'onboarding.current_learning.speaking': 'Parlando con altre persone',
    'onboarding.current_learning.not_learning': 'Non sto imparando attualmente',
    'onboarding.main_goal.question': 'Qual è il tuo obiettivo principale per migliorare il tuo spagnolo?',
    'onboarding.main_goal.work': 'Lavoro',
    'onboarding.main_goal.living_abroad': 'Vivere all\'estero',
    'onboarding.main_goal.traveling': 'Viaggiare',
    'onboarding.main_goal.skills': 'Sviluppare le mie capacità',
    'onboarding.main_goal.friends': 'Parlare con gli amici',
    'onboarding.main_goal.studying': 'Studiare',
    'onboarding.speaking_frequency.question': 'Quanto spesso parli spagnolo nella tua vita quotidiana?',
    'onboarding.speaking_frequency.everyday': 'Ogni giorno',
    'onboarding.speaking_frequency.few_week': 'Alcuni giorni alla settimana',
    'onboarding.speaking_frequency.few_month': 'Alcuni giorni al mese',
    'onboarding.speaking_frequency.never': 'Mai',
    'onboarding.fear.question': 'Hai paura di sembrare sciocco quando parli spagnolo?',
    'onboarding.fear.no': 'No',
    'onboarding.fear.maybe': 'Forse',
    'onboarding.fear.yes': 'Sì',
    'onboarding.improvement.question': 'Dove vuoi migliorare?',
    'onboarding.improvement.speaking': 'Parlare con sicurezza',
    'onboarding.improvement.pronunciation': 'Migliorare la pronuncia',
    'onboarding.improvement.vocabulary': 'Arricchire il vocabolario',
    'onboarding.improvement.grammar': 'Essere bravo in grammatica',
    'onboarding.improvement.understanding': 'Capire i madrelingua',
    'onboarding.improvement.writing': 'Scrivere con più fluidità',
    'onboarding.improvement.else': 'Qualcos\'altro',
    'onboarding.interests.question': 'Quali argomenti ti interessano?',
    'onboarding.interests.subtitle': 'Renderemo la tua pratica dello spagnolo più divertente',
    'onboarding.interests.memes': 'Memes',
    'onboarding.interests.humor': 'Umorismo',
    'onboarding.interests.tech': 'Tecnologia',
    'onboarding.interests.business': 'Business',
    'onboarding.interests.games': 'Videogiochi',
    'onboarding.interests.music': 'Musica',
    'onboarding.interests.movies': 'Film',
    'onboarding.interests.news': 'Notizie',
    'onboarding.interests.books': 'Libri',
    'onboarding.interests.podcasts': 'Podcast',
    'onboarding.interests.fitness': 'Fitness',
    'onboarding.interests.food': 'Cibo',
    'onboarding.interests.crafts': 'Artigianato',
    'onboarding.interests.travel': 'Viaggi',
    'onboarding.interests.science': 'Scienza',
    'onboarding.commitment.question': 'Qual è il tuo impegno per progredire?',
    'onboarding.commitment.7_days': 'Serie di 7 giorni',
    'onboarding.commitment.14_days': 'Serie di 14 giorni',
    'onboarding.commitment.30_days': 'Serie di 30 giorni',
    'onboarding.commitment.50_days': 'Serie di 50 giorni',
    'onboarding.commitment.promising': 'Promettente',
    'onboarding.commitment.determined': 'Determinato',
    'onboarding.commitment.impressive': 'Impressionante',
    'onboarding.commitment.unstoppable': 'Inarrestabile',
    'onboarding.motivation.title': 'Impegno di motivazione',
    'onboarding.motivation.message': 'Per raggiungere ciò che voglio, devo progredire.\n\nQuindi mi impegno a raggiungere i miei obiettivi e a migliorarmi.\n\nE mi fido di Sofia per guidarmi lungo il percorso e aiutarmi a parlare spagnolo fluentemente.',
    'onboarding.motivation.press_hold': 'Premi e tieni',
    'onboarding.future.title': 'Sono io',
    'onboarding.future.sender': 'Tu del futuro',
    'onboarding.future.date': '15 novembre 2025',
    'onboarding.future.message': 'Sì, sei tu del futuro. Ti scrivo dal 2025 perché oggi è un giorno importante per te. Per noi!\n\nIl 15 novembre 2025 è il giorno in cui abbiamo cambiato le nostre vite.\n\nOggi mi sento benissimo e parlo spagnolo fluentemente. Grazie alla decisione di sviluppo personale che stai per prendere.\n\nA presto,\nTu del futuro',
    'onboarding.plan.title': 'Sto creando il tuo piano di studio personalizzato',
    'onboarding.plan.subtitle': 'Adattato al tuo livello e alle tue esigenze',
    'onboarding.plan.message': 'Usare materiali legati ai tuoi interessi migliora l\'apprendimento del vocabolario del 30%.',
    'onboarding.plan.sofia': 'Ogni lezione è costruita da ciò di cui discuti con me.',
    'onboarding.comparison.title': 'Ti fanno cliccare, Sofia ti fa parlare',
    'onboarding.notifications.question': 'Con me, non dimenticherai di esercitarti',
    'onboarding.first_session': 'Incredibile—il tuo allenamento inizia ufficialmente 🎉 Ora ti farò domande vere, e risponderai in spagnolo. Pronto per la tua prima mini-conversazione?',
  },
  pt: {
    // Onboarding
    'onboarding.spanish_level': 'Qual é o seu nível de espanhol?',
    'onboarding.spanish_level.beginner': 'Iniciante',
    'onboarding.spanish_level.elementary': 'Elementar',
    'onboarding.spanish_level.intermediate': 'Intermediário',
    'onboarding.spanish_level.advanced': 'Avançado',
    'onboarding.spanish_level.native': 'Nativo',
    'onboarding.native_language': 'Qual é o seu idioma nativo?',
    'onboarding.name': 'Qual é o seu nome?',
    'onboarding.gender': 'Qual é o seu gênero?',
    'onboarding.age': 'Quantos anos você tem?',
    'onboarding.next': 'PRÓXIMO',
    'onboarding.close': 'Fechar',
    // Home
    'home.greeting': 'Olá',
    'home.take_first_lesson': 'Faça sua primeira lição',
    'home.unlock_key': 'para desbloquear uma chave',
    'home.call': 'CHAMADA',
    'home.level': 'NÍVEL',
    'home.quests': 'MISSÕES',
    'lesson.say_in_spanish': 'DIGA EM ESPANHOL',
    'lesson.learn': 'APRENDER',
    'lesson.feedback.correct': 'Excelente! Você disse "{answer}". Muito bem feito.',
    'lesson.feedback.incorrect': 'Não está correto. Você disse "{answer}". Tente novamente.',
    'quests.title': 'Missões',
    'quests.quest1.title': 'Complete sua primeira lição',
    'quests.quest1.description': 'Termine sua primeira lição para desbloquear uma chave',
    'quests.quest2.title': 'Pratique 5 dias seguidos',
    'quests.quest2.description': 'Mantenha sua sequência por 5 dias',
    'quests.quest3.title': 'Domine 10 palavras',
    'quests.quest3.description': 'Aprenda e domine 10 palavras novas',
    'quests.completed': '✓ Concluído',
    // Paywall
    'paywall.access_sofia': 'acesse Sofia',
    'paywall.trial_text': '7 dias grátis, depois $99.99 ($8.33/mês)',
    'paywall.annual': 'Anual',
    'paywall.monthly': 'Mensal',
    'paywall.today': 'Hoje',
    'paywall.in_5_days': 'Em 5 dias',
    'paywall.in_7_days': 'Em 7 dias',
    'paywall.unlock_practice': 'Desbloqueie prática ilimitada com Sofia, todas as lições e mais.',
    'paywall.reminder_trial': 'Enviaremos um lembrete de que seu teste está terminando em breve.',
    'paywall.charged_cancel': 'Você será cobrado, cancele a qualquer momento antes.',
    'paywall.no_payment_due': 'NENHUM PAGAMENTO NECESSÁRIO AGORA',
    'paywall.start_free_trial': 'INICIAR MINHA AVALIAÇÃO GRÁTIS',
    'paywall.testimonial1': '"Sofia me ajudou a falar espanhol em 2 semanas!" - Marie',
    'paywall.testimonial2': '"O melhor app para aprender espanhol." - Thomas',
    'paywall.testimonial3': '"Eu progresso todos os dias graças à Sofia." - Sophie',
    // Chat
    'chat.placeholder': 'Digite uma mensagem...',
    'chat.listening': 'Ouvindo...',
    // Call End
    'call.end.title': 'Chamada encerrada',
    'call.end.subtitle': 'Você precisa voltar ao caminho certo!',
    'call.end.xp': 'XP',
    'call.end.gems': 'GEMAS',
    'call.end.next': 'PRÓXIMO',
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    // Onboarding - Questions et options
    'onboarding.placeholder.name': 'Digite seu nome',
    'onboarding.gender.male': 'Masculino',
    'onboarding.gender.female': 'Feminino',
    'onboarding.gender.prefer_not': 'Prefiro não dizer',
    'onboarding.age.under_18': 'Menos de 18',
    'onboarding.age.18_24': '18 - 24',
    'onboarding.age.25_34': '25 - 34',
    'onboarding.age.35_54': '35 - 54',
    'onboarding.age.55_over': '55 e mais',
    'onboarding.age.prefer_not': 'Prefiro não dizer',
    'onboarding.current_learning.question': 'Como você está melhorando seu espanhol atualmente?',
    'onboarding.current_learning.courses': 'Cursos ou treinamento',
    'onboarding.current_learning.apps': 'Aplicativos de idiomas',
    'onboarding.current_learning.videos': 'Vídeos ou filmes',
    'onboarding.current_learning.podcasts': 'Podcasts ou audiolivros',
    'onboarding.current_learning.speaking': 'Falando com outras pessoas',
    'onboarding.current_learning.not_learning': 'Não estou aprendendo atualmente',
    'onboarding.main_goal.question': 'Qual é o seu objetivo principal para melhorar seu espanhol?',
    'onboarding.main_goal.work': 'Trabalho',
    'onboarding.main_goal.living_abroad': 'Viver no exterior',
    'onboarding.main_goal.traveling': 'Viajar',
    'onboarding.main_goal.skills': 'Desenvolver minhas habilidades',
    'onboarding.main_goal.friends': 'Falar com amigos',
    'onboarding.main_goal.studying': 'Estudar',
    'onboarding.speaking_frequency.question': 'Com que frequência você fala espanhol na sua vida diária?',
    'onboarding.speaking_frequency.everyday': 'Todos os dias',
    'onboarding.speaking_frequency.few_week': 'Alguns dias por semana',
    'onboarding.speaking_frequency.few_month': 'Alguns dias por mês',
    'onboarding.speaking_frequency.never': 'Nunca',
    'onboarding.fear.question': 'Você tem medo de parecer bobo quando fala espanhol?',
    'onboarding.fear.no': 'Não',
    'onboarding.fear.maybe': 'Talvez',
    'onboarding.fear.yes': 'Sim',
    'onboarding.improvement.question': 'Onde você quer melhorar?',
    'onboarding.improvement.speaking': 'Falar com confiança',
    'onboarding.improvement.pronunciation': 'Melhorar a pronúncia',
    'onboarding.improvement.vocabulary': 'Enriquecer o vocabulário',
    'onboarding.improvement.grammar': 'Ser bom em gramática',
    'onboarding.improvement.understanding': 'Entender falantes nativos',
    'onboarding.improvement.writing': 'Escrever com mais fluência',
    'onboarding.improvement.else': 'Algo mais',
    'onboarding.interests.question': 'Quais tópicos te interessam?',
    'onboarding.interests.subtitle': 'Tornaremos sua prática de espanhol mais divertida',
    'onboarding.interests.memes': 'Memes',
    'onboarding.interests.humor': 'Humor',
    'onboarding.interests.tech': 'Tecnologia',
    'onboarding.interests.business': 'Negócios',
    'onboarding.interests.games': 'Videogames',
    'onboarding.interests.music': 'Música',
    'onboarding.interests.movies': 'Filmes',
    'onboarding.interests.news': 'Notícias',
    'onboarding.interests.books': 'Livros',
    'onboarding.interests.podcasts': 'Podcasts',
    'onboarding.interests.fitness': 'Fitness',
    'onboarding.interests.food': 'Comida',
    'onboarding.interests.crafts': 'Artesanato',
    'onboarding.interests.travel': 'Viagens',
    'onboarding.interests.science': 'Ciência',
    'onboarding.commitment.question': 'Qual é o seu compromisso para progredir?',
    'onboarding.commitment.7_days': 'Sequência de 7 dias',
    'onboarding.commitment.14_days': 'Sequência de 14 dias',
    'onboarding.commitment.30_days': 'Sequência de 30 dias',
    'onboarding.commitment.50_days': 'Sequência de 50 dias',
    'onboarding.commitment.promising': 'Promissor',
    'onboarding.commitment.determined': 'Determinado',
    'onboarding.commitment.impressive': 'Impressionante',
    'onboarding.commitment.unstoppable': 'Imparável',
    'onboarding.motivation.title': 'Compromisso de motivação',
    'onboarding.motivation.message': 'Para alcançar o que quero, devo progredir.\n\nPortanto, me comprometo a alcançar meus objetivos e me melhorar.\n\nE confio em Sofia para me guiar no caminho e me ajudar a falar espanhol fluentemente.',
    'onboarding.motivation.press_hold': 'Pressione e segure',
    'onboarding.future.title': 'Sou eu',
    'onboarding.future.sender': 'Você do futuro',
    'onboarding.future.date': '15 de novembro de 2025',
    'onboarding.future.message': 'Sim, é você do futuro. Estou escrevendo para você de 2025 porque hoje é um dia importante para você. Para nós!\n\n15 de novembro de 2025 é o dia em que mudamos nossas vidas.\n\nHoje me sinto ótimo e falo espanhol fluentemente. Graças à decisão de desenvolvimento pessoal que você está prestes a tomar.\n\nAté logo,\nVocê do futuro',
    'onboarding.plan.title': 'Estou criando seu plano de estudo personalizado',
    'onboarding.plan.subtitle': 'Adaptado ao seu nível e necessidades',
    'onboarding.plan.message': 'Usar materiais relacionados aos seus interesses melhora o aprendizado de vocabulário em 30%.',
    'onboarding.plan.sofia': 'Cada lição é construída a partir do que você discute comigo.',
    'onboarding.comparison.title': 'Eles fazem você clicar, Sofia faz você falar',
    'onboarding.notifications.question': 'Comigo, você não esquecerá de praticar',
    'onboarding.first_session': 'Incrível—seu treinamento começa oficialmente 🎉 Agora vou fazer perguntas reais, e você responderá em espanhol. Pronto para sua primeira mini-conversa?',
  },
};

// Mapping des noms de langues vers les codes
const languageMap: Record<string, AppLanguage> = {
  'Français': 'fr',
  'English': 'en',
  'Deutsch': 'de',
  'Italiano': 'it',
  'Português': 'pt',
};

export function getLanguageCode(languageName: string): AppLanguage {
  return languageMap[languageName] || 'en';
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<AppLanguage>('en'); // Par défaut en anglais

  useEffect(() => {
    // Charger la langue sauvegardée au démarrage, mais garder 'en' par défaut
    const loadLanguage = async () => {
      try {
        const savedLanguage = await getStorageItem('app_language');
        
        // Seulement charger la langue sauvegardée si elle existe, sinon garder 'en' (anglais) par défaut
        if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en' || savedLanguage === 'de' || savedLanguage === 'es' || savedLanguage === 'it' || savedLanguage === 'pt')) {
          setLanguageState(savedLanguage as AppLanguage);
        }
        // Sinon, on garde 'en' qui est déjà la valeur par défaut
      } catch (error: any) {
        // Ignorer silencieusement toutes les erreurs - l'app continue avec la langue par défaut
        // L'app continue avec 'en' par défaut
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: AppLanguage) => {
    // Toujours mettre à jour l'état immédiatement pour une meilleure UX
    setLanguageState(lang);
    
    // Essayer de sauvegarder en arrière-plan, mais ne pas bloquer si ça échoue
    try {
      await setStorageItem('app_language', lang);
      console.log('✅ Language saved successfully:', lang);
    } catch (error: any) {
      // Ignorer silencieusement toutes les erreurs - l'état est déjà mis à jour
      // L'état a déjà été mis à jour, donc l'app fonctionne normalement
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

